### ISSUE TITLE
Preview is convoluted when page contains several bullets

### ISSUE THREAD

**Issue by jiewangjs** [marzwipan/TexFlowyTM#3]
![image](https://user-images.githubusercontent.com/11204422/227191473-1bdc4ef6-f374-4122-bffb-6e17ce7c34c8.png)
The above will generate following:
![image](https://user-images.githubusercontent.com/11204422/227191575-f6b79439-7619-4480-9929-75639adbfb5c.png)
I also tried your @Zwierlein previous implementation in another git, it doesn't have this problem, but the rendering is not responsive compared to this one.

**Comment by marzwipan** [comment]
Hi, just seeing this. Is it ok now?

**Comment by jiewangjs** [comment]
Thanks for your attention, I took some time and modified some css rule, and it's ok now. I realized the causing of this problem may not be this script, so I closed it actively. 


|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 3/23/2023 23:08 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
State ***@***.***> |
| Subject | Re: [marzwipan/TexFlowyTM] Preview is convoluted when page contains several bullets (Issue #3) |

Hi, just seeing this. Is it ok now?
